# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creator_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Creator_Form(object):
    def setupUi(self, Creator_Form):
        Creator_Form.setObjectName("Creator_Form")
        Creator_Form.resize(433, 291)
        self.label_1 = QtWidgets.QLabel(Creator_Form)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_1.setObjectName("label_1")
        self.line = QtWidgets.QFrame(Creator_Form)
        self.line.setGeometry(QtCore.QRect(10, 240, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_1 = QtWidgets.QPushButton(Creator_Form)
        self.pushButton_1.setGeometry(QtCore.QRect(270, 260, 75, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Creator_Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 260, 71, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_1 = QtWidgets.QComboBox(Creator_Form)
        self.comboBox_1.setGeometry(QtCore.QRect(80, 10, 61, 22))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.label_2 = QtWidgets.QLabel(Creator_Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Creator_Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 47, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(80, 40, 141, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 70, 141, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(Creator_Form)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 61, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 100, 141, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Creator_Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 61, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 130, 141, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(Creator_Form)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(Creator_Form)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 160, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_7 = QtWidgets.QLabel(Creator_Form)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 61, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 190, 141, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(Creator_Form)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 61, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(Creator_Form)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 220, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(Creator_Form)
        self.label_9.setGeometry(QtCore.QRect(230, 100, 51, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Creator_Form)
        self.label_10.setGeometry(QtCore.QRect(230, 130, 51, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 100, 51, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(280, 130, 51, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_11 = QtWidgets.QLabel(Creator_Form)
        self.label_11.setGeometry(QtCore.QRect(340, 100, 21, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Creator_Form)
        self.label_12.setGeometry(QtCore.QRect(340, 130, 21, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(370, 100, 51, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Creator_Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(370, 130, 51, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")

        self.retranslateUi(Creator_Form)
        QtCore.QMetaObject.connectSlotsByName(Creator_Form)

    def retranslateUi(self, Creator_Form):
        _translate = QtCore.QCoreApplication.translate
        Creator_Form.setWindowTitle(_translate("Creator_Form", "Form"))
        self.label_1.setText(_translate("Creator_Form", "Protocol:"))
        self.pushButton_1.setText(_translate("Creator_Form", "Reset"))
        self.pushButton_2.setText(_translate("Creator_Form", "Add"))
        self.comboBox_1.setItemText(0, _translate("Creator_Form", "None"))
        self.comboBox_1.setItemText(1, _translate("Creator_Form", "TCP"))
        self.comboBox_1.setItemText(2, _translate("Creator_Form", "UDP"))
        self.comboBox_1.setItemText(3, _translate("Creator_Form", "ICMP"))
        self.comboBox_1.setItemText(4, _translate("Creator_Form", "UDPLIGHT"))
        self.comboBox_1.setItemText(5, _translate("Creator_Form", "ESP"))
        self.comboBox_1.setItemText(6, _translate("Creator_Form", "AH"))
        self.comboBox_1.setItemText(7, _translate("Creator_Form", "SCTP"))
        self.comboBox_1.setItemText(8, _translate("Creator_Form", "GRE"))
        self.label_2.setText(_translate("Creator_Form", "Input:"))
        self.label_3.setText(_translate("Creator_Form", "Output:"))
        self.lineEdit_1.setPlaceholderText(_translate("Creator_Form", "eth0"))
        self.lineEdit_2.setPlaceholderText(_translate("Creator_Form", "wlan0"))
        self.label_4.setText(_translate("Creator_Form", "Dest:"))
        self.lineEdit_3.setPlaceholderText(_translate("Creator_Form", "8.8.0.0/16"))
        self.label_5.setText(_translate("Creator_Form", "Source:"))
        self.lineEdit_4.setPlaceholderText(_translate("Creator_Form", "10.10.0.0/16"))
        self.label_6.setText(_translate("Creator_Form", "State:"))
        self.comboBox_2.setItemText(0, _translate("Creator_Form", "None"))
        self.comboBox_2.setItemText(1, _translate("Creator_Form", "NEW"))
        self.comboBox_2.setItemText(2, _translate("Creator_Form", "ESTABLISHED"))
        self.comboBox_2.setItemText(3, _translate("Creator_Form", "RELATED"))
        self.comboBox_2.setItemText(4, _translate("Creator_Form", "INVALID"))
        self.comboBox_2.setItemText(5, _translate("Creator_Form", "UNTRACKED"))
        self.label_7.setText(_translate("Creator_Form", "Limit:"))
        self.label_8.setText(_translate("Creator_Form", "Action:"))
        self.comboBox_3.setItemText(0, _translate("Creator_Form", "ACCEPT"))
        self.comboBox_3.setItemText(1, _translate("Creator_Form", "DROP"))
        self.comboBox_3.setItemText(2, _translate("Creator_Form", "REJECT"))
        self.comboBox_3.setItemText(3, _translate("Creator_Form", "DNAT"))
        self.comboBox_3.setItemText(4, _translate("Creator_Form", "SNAT"))
        self.comboBox_3.setItemText(5, _translate("Creator_Form", "MARK"))
        self.comboBox_3.setItemText(6, _translate("Creator_Form", "LOG"))
        self.comboBox_3.setItemText(7, _translate("Creator_Form", "MASQUERADE"))
        self.comboBox_3.setItemText(8, _translate("Creator_Form", "IPV4OPTSSTRIP"))
        self.comboBox_3.setItemText(9, _translate("Creator_Form", "TARPIT"))
        self.comboBox_3.setItemText(10, _translate("Creator_Form", "NOTRACK"))
        self.comboBox_3.setItemText(11, _translate("Creator_Form", "MIRROR"))
        self.comboBox_3.setItemText(12, _translate("Creator_Form", "REDIRECT"))
        self.comboBox_3.setItemText(13, _translate("Creator_Form", "RETURN"))
        self.comboBox_3.setItemText(14, _translate("Creator_Form", "TOS"))
        self.comboBox_3.setItemText(15, _translate("Creator_Form", "TTL"))
        self.label_9.setText(_translate("Creator_Form", "From:"))
        self.label_10.setText(_translate("Creator_Form", "From:"))
        self.label_11.setText(_translate("Creator_Form", "To:"))
        self.label_12.setText(_translate("Creator_Form", "To:"))

