# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_Form(object):
    def setupUi(self, Main_Form):
        Main_Form.setObjectName("Main_Form")
        Main_Form.setEnabled(True)
        Main_Form.resize(753, 469)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main_Form.sizePolicy().hasHeightForWidth())
        Main_Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_Form.setWindowIcon(icon)
        self.tabWidget_main = QtWidgets.QTabWidget(Main_Form)
        self.tabWidget_main.setGeometry(QtCore.QRect(0, 0, 771, 61))
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_1.setFont(font)
        self.tab_1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tab_1.setObjectName("tab_1")
        self.tabWidget_1 = QtWidgets.QTabWidget(self.tab_1)
        self.tabWidget_1.setGeometry(QtCore.QRect(0, 0, 771, 41))
        self.tabWidget_1.setObjectName("tabWidget_1")
        self.tab_1_1 = QtWidgets.QWidget()
        self.tab_1_1.setObjectName("tab_1_1")
        self.tabWidget_1.addTab(self.tab_1_1, "")
        self.tab_1_2 = QtWidgets.QWidget()
        self.tab_1_2.setObjectName("tab_1_2")
        self.tabWidget_1.addTab(self.tab_1_2, "")
        self.tab_1_3 = QtWidgets.QWidget()
        self.tab_1_3.setObjectName("tab_1_3")
        self.tabWidget_1.addTab(self.tab_1_3, "")
        self.tabWidget_main.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2_1 = QtWidgets.QWidget()
        self.tab_2_1.setObjectName("tab_2_1")
        self.tabWidget_2.addTab(self.tab_2_1, "")
        self.tab_2_2 = QtWidgets.QWidget()
        self.tab_2_2.setObjectName("tab_2_2")
        self.tabWidget_2.addTab(self.tab_2_2, "")
        self.tab_2_3 = QtWidgets.QWidget()
        self.tab_2_3.setObjectName("tab_2_3")
        self.tabWidget_2.addTab(self.tab_2_3, "")
        self.tabWidget_main.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3_1 = QtWidgets.QWidget()
        self.tab_3_1.setObjectName("tab_3_1")
        self.tabWidget_3.addTab(self.tab_3_1, "")
        self.tab_3_2 = QtWidgets.QWidget()
        self.tab_3_2.setObjectName("tab_3_2")
        self.tabWidget_3.addTab(self.tab_3_2, "")
        self.tabWidget_main.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_4_1 = QtWidgets.QWidget()
        self.tab_4_1.setObjectName("tab_4_1")
        self.tabWidget_4.addTab(self.tab_4_1, "")
        self.tab_4_2 = QtWidgets.QWidget()
        self.tab_4_2.setObjectName("tab_4_2")
        self.tabWidget_4.addTab(self.tab_4_2, "")
        self.tabWidget_main.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 761, 421))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_5_1 = QtWidgets.QWidget()
        self.tab_5_1.setObjectName("tab_5_1")
        self.tabWidget_5.addTab(self.tab_5_1, "")
        self.tab_5_2 = QtWidgets.QWidget()
        self.tab_5_2.setObjectName("tab_5_2")
        self.tabWidget_5.addTab(self.tab_5_2, "")
        self.tabWidget_main.addTab(self.tab_5, "")
        self.tableWidget = QtWidgets.QTableWidget(Main_Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 751, 351))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/set/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.lineEdit = QtWidgets.QLineEdit(Main_Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 430, 511, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_1 = QtWidgets.QPushButton(Main_Form)
        self.pushButton_1.setGeometry(QtCore.QRect(590, 430, 121, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Main_Form)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 430, 31, 23))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/make_img/make.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Main_Form)
        self.label.setGeometry(QtCore.QRect(10, 430, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.actionmake_image = QtWidgets.QAction(Main_Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("make.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmake_image.setIcon(icon3)
        self.actionmake_image.setObjectName("actionmake_image")
        self.actiondelete_image = QtWidgets.QAction(Main_Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondelete_image.setIcon(icon4)
        self.actiondelete_image.setObjectName("actiondelete_image")

        self.retranslateUi(Main_Form)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_1.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main_Form)
        Main_Form.setTabOrder(self.tabWidget_main, self.tabWidget_1)

    def retranslateUi(self, Main_Form):
        _translate = QtCore.QCoreApplication.translate
        Main_Form.setWindowTitle(_translate("Main_Form", "Form"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_1_1), _translate("Main_Form", "filter"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_1_2), _translate("Main_Form", "nat"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_1_3), _translate("Main_Form", "mangle"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_1), _translate("Main_Form", "INPUT"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2_1), _translate("Main_Form", "filter"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2_2), _translate("Main_Form", "nat"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2_3), _translate("Main_Form", "mangle"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_2), _translate("Main_Form", "OUTPUT"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3_1), _translate("Main_Form", "filter"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3_2), _translate("Main_Form", "mangle"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_3), _translate("Main_Form", "FORWARD"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4_1), _translate("Main_Form", "nat"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4_2), _translate("Main_Form", "mangle"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_4), _translate("Main_Form", "PREROUTING"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_5_1), _translate("Main_Form", "nat"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_5_2), _translate("Main_Form", "mangle"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_5), _translate("Main_Form", "POSTROUTING"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main_Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main_Form", "Rule"))
        self.pushButton_1.setText(_translate("Main_Form", "Creator"))
        self.label.setText(_translate("Main_Form", "Add Rule"))
        self.actionmake_image.setText(_translate("Main_Form", "make_image"))
        self.actiondelete_image.setText(_translate("Main_Form", "delete_image"))

